name: flutter_scalable_ocr
description: Flutter scalable OCR package is a wrapper around google_mlkit_text_recognition where you can partialy select part of camera which text will be processed of.
version: 2.2.0
homepage: https://github.com/vbalagovic/flutter_scalable_ocr.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1. DEPENDA APENAS DOS PLUGINS PRINCIPAIS QUE VOCÊ IMPORTA NO DART

  # Pega o 'camera' (interface Dart) do seu fork
  camera:
    git:
      url: https://github.com/KauaOrtiz/packages.git
      ref: main
      path: packages/camera/camera

  # Pega o 'text_recognition' (interface Dart) do seu fork
  google_mlkit_text_recognition:
    git:
      url: https://github.com/KauaOrtiz/google_ml_kit_flutter.git
      path: packages/google_mlkit_text_recognition

  #camera: 0.11.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.1

#dependency_overrides:
#  camera_android_camerax:
#    git:
#      url: https://github.com/KauaOrtiz/packages.git
#      ref: main
#      path: packages/camera/camera_android_camerax


# 2. ADICIONE ESTE BLOCO PARA FORÇAR AS IMPLEMENTAÇÕES NATIVAS
#dependency_overrides:
#  # Força o 'camera' (do seu app) a usar esta implementação nativa do seu fork
#  camera_android:
#    git:
#      url: https://github.com/KauaOrtiz/packages.git
#      ref: main
#      path: packages/camera/camera_android
#
#  # Força o 'camera' (do seu app) a usar esta implementação nativa do seu fork
#  camera_avfoundation:
#    git:
#      url: https://github.com/KauaOrtiz/packages.git
#      ref: main
#      path: packages/camera/camera_avfoundation

# 3. REMOVA O BLOCO 'flutter: plugin:' INTEIRO (como fizemos antes)
# flutter:
#   plugin:
#     ...